import argparse
import json
from pathlib import Path

from langgraph.types import Command

from ontoproduct.graph.state import initial_state
from ontoproduct.graph.workflow import build_workflow


def main():
    parser = argparse.ArgumentParser(description="OntoProduct PHASE 1 mock workflow")
    parser.add_argument(
        "--interactive", action="store_true", help="Read resume commands as JSON"
    )
    parser.add_argument(
        "--diagram", type=Path, help="Write Mermaid generated by the compiled graph"
    )
    args = parser.parse_args()
    graph = build_workflow()
    if args.diagram:
        args.diagram.parent.mkdir(parents=True, exist_ok=True)
        args.diagram.write_text(graph.get_graph().draw_mermaid(), encoding="utf-8")
        print(f"Generated diagram: {args.diagram}")
        return
    config = {
        "configurable": {"thread_id": "cli-registration-case"},
        "recursion_limit": 100,
    }
    request = initial_state(case_id="cli-registration-case")
    while True:
        for mode, event in graph.stream(
            request, config, stream_mode=["custom", "updates"]
        ):
            if mode == "custom":
                print(
                    f"{event['event']}: {event['agent']} {event['status']} attempt={event['attempt']}"
                )
        snapshot = graph.get_state(config)
        pending = [i for task in snapshot.tasks for i in task.interrupts]
        if not pending:
            print(
                json.dumps(
                    {
                        "case_status": snapshot.values["case_status"],
                        "final_product": snapshot.values.get("final_product"),
                    },
                    ensure_ascii=False,
                    indent=2,
                )
            )
            return
        payload = pending[0].value
        print("INTERRUPT " + json.dumps(payload, ensure_ascii=False))
        if args.interactive:
            while True:
                try:
                    answer = json.loads(input("Resume JSON> "))
                    break
                except json.JSONDecodeError:
                    print("Invalid JSON; the checkpoint is still suspended.")
        elif payload["kind"] == "error":
            answer = {"action": "STOP"}
        elif payload["review"]["can_register"]:
            answer = {"action": "APPROVE"}
        else:
            answer = {
                "action": "EDIT",
                "edits": {"attributes.rated_speed": {"value": 3000, "unit": "rpm"}},
            }
        print("RESUME " + json.dumps(answer))
        request = Command(resume=answer)


if __name__ == "__main__":
    main()
