[theme]
primaryColor = "#087f8c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f7fa"
textColor = "#182536"
font = "sans serif"

[server]
maxUploadSize = 20
headless = true

[browser]
gatherUsageStats = false
